### Get All Students
GET http://localhost:8080/academics/api/students/all
Accept: application/json

### Get Student 2
GET http://localhost:8080/academics/api/students/danielz3
Accept: application/json

### Get Student 2 Subjects
GET http://localhost:8080/academics/api/students/danielz3/subjects
Accept: application/json


### Create A New Student
POST http://localhost:8080/academics/api/students
Content-Type: application/json

{
"email": "johndoe@mail.com",
"name": "John Doe",
"username": "john",
"password": "jd",
"courseCode": 1
}


### Send a Email
POST http://localhost:8080/academics/api/students/danielz3/email
Content-Type: application/json

{
  "subject": "PUT ME OUT ME FUCKYYY MESSORRRYYYYY",
  "body": "put me OUT A MY MISSERYYYY"
}


### REQUEST JWT TOKEN
POST http://localhost:8080/academics/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "danielz33", "password": "daniel3" }

### GET ALL STUDENTS
GET http://localhost:8080/academics/api/students/all
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJkYW5pZWx6MzMiLCJpYXQiOjE3MzA4NDYyNTksImV4cCI6MTczMDg0OTg1OX0.bSB_KUV8lmhbeWSM8FW724U4yNqeCqpLvgWbu-tieBZnWHVMjNdPcjfii67uTrNj
