### Get All Students
GET http://localhost:8080/academics/api/students/all
Accept: application/json

### Get Student 2
GET http://localhost:8080/academics/api/students/danielz3
Accept: application/json

### Get Student 2 Subjects
GET http://localhost:8080/academics/api/students/danielz3/subjects
Accept: application/json


### Create A New Student
POST http://localhost:8080/academics/api/students
Content-Type: application/json

{
"email": "johndoe@mail.com",
"name": "John Doe",
"username": "john",
"password": "jd",
"courseCode": 1
}


### Send a Email
POST http://localhost:8080/academics/api/students/danielz3/email
Content-Type: application/json

{
  "subject": "PUT ME OUT ME FUCKYYY MESSORRRYYYYY",
  "body": "put me OUT A MY MISSERYYYY"
}
